import type { SpeciesSprites } from "./types";

// Bunny, fills only (the outline is added at load). b fur, g grey points
// (ear tips, toes, back patch), d belly shade, S far-side legs (unoutlined),
// w cotton tail and eye shine, e eye, z closed eye, p nose and inner ear,
// k cheek blush, o interior line. "walk" is a hop: ground, push, air, land.
export const bunny: SpeciesSprites = {
  variants: {
    white: {
      label: "White",
      colors: { b: "#ece6dc", S: "#c4baae", w: "#ffffff", g: "#a89d91", d: "#d8d0c4", k: "#f2b8c0", z: "#1f1a17", e: "#1f1a17", p: "#eba3b1" },
      outline: { light: "#4a4038", dark: "#8a7f74" },
    },
    brown: {
      label: "Brown",
      colors: { b: "#b98e66", S: "#9a7653", w: "#f6efe6", g: "#7f5c40", d: "#a37c57", k: "#e9a3a8", z: "#1f1a17", e: "#1f1a17", p: "#e9a3b0" },
      outline: { light: "#3e2c1f", dark: "#6e5038" },
    },
    grey: {
      label: "Grey",
      colors: { b: "#a7a5ab", S: "#8a888f", w: "#f4f4f6", g: "#6f6d74", d: "#918f96", k: "#e9b0b8", z: "#1f1a17", e: "#1f1a17", p: "#eba3b1" },
      outline: { light: "#2f2e33", dark: "#66646b" },
    },
  },
  frames: {
    idle1: [
      "................",
      "................",
      "................",
      ".......gg...gg..",
      ".......bp...pb..",
      ".......bp...pb..",
      ".......bbbbbbb..",
      ".......bbbbbbbb.",
      ".......bwebbweb.",
      "....bbbbeebbeeb.",
      "...bbbbbbbbppbb.",
      "..wbbbbbbbbbbb..",
      "..wbbbbbbbbbb...",
      "...dddddddbbb...",
      "...bbgS...Sb....",
      "................",
    ],
    idle2: [
      "................",
      "................",
      "................",
      ".......gg...gg..",
      ".......bp...pb..",
      ".......bp...pb..",
      ".......bbbbbbb..",
      ".......bbbbbbbb.",
      ".......bbbbbbbb.",
      "....bbbbzzbbzzb.",
      "...bbbbbbbbppbb.",
      "..wbbbbbbbbbbb..",
      "..wbbbbbbbbbb...",
      "...dddddddbbb...",
      "...bbgS...Sb....",
      "................",
    ],
    sit: [
      "................",
      "................",
      "................",
      ".......gg...gg..",
      ".......bp...pb..",
      ".......bp...pb..",
      ".......bbbbbbb..",
      ".......bbbbbbbb.",
      ".......bwebbweb.",
      ".....bbbeebbeeb.",
      "....bbbbbbbppbb.",
      "...wbbbbbbbbbb..",
      "...wbbbbbbbbb...",
      "....bbbbbbbbb...",
      "...bbgbbobbb....",
      "................",
    ],
    walk1: [
      "................",
      "................",
      "................",
      ".......gg...gg..",
      ".......bp...pb..",
      ".......bp...pb..",
      ".......bbbbbbb..",
      ".......bbbbbbbb.",
      ".......bwebbweb.",
      "....bbbbeebbeeb.",
      "...bbbbbbbbppbb.",
      "..wbbbbbbbbbbb..",
      "..wbbbbbbbbbb...",
      "...dddddddbbb...",
      "...bbgS...Sb....",
      "................",
    ],
    walk2: [
      "................",
      "................",
      ".......gg...gg..",
      ".......bp...pb..",
      ".......bp...pb..",
      ".......bbbbbbb..",
      ".......bbbbbbbb.",
      ".......bwebbweb.",
      "....bbbbeebbeeb.",
      "...bbbbbbbbppbb.",
      "..wbbbbbbbbbbb..",
      "..wbbbbbbbbbb...",
      "...dddddddbbb...",
      "...bS.....Sb....",
      "..bb............",
      "................",
    ],
    walk3: [
      "................",
      "................",
      ".......gg...gg..",
      ".......bp...pb..",
      ".......bp...pb..",
      ".......bbbbbbb..",
      ".......bbbbbbbb.",
      ".......bwebbweb.",
      "....bbbbeebbeeb.",
      "...bbbbbbbbppbb.",
      "..wbbbbbbbbbbb..",
      "..wbbbbbbbbbb...",
      "...dddddddbbb...",
      "..bS.......Sb...",
      ".bS.............",
      "................",
    ],
    walk4: [
      "................",
      "................",
      "................",
      ".......gg...gg..",
      ".......bp...pb..",
      ".......bp...pb..",
      ".......bbbbbbb..",
      ".......bbbbbbbb.",
      ".......bwebbweb.",
      "....bbbbeebbeeb.",
      "...bbbbbbbbppbb.",
      "..wbbbbbbbbbbb..",
      "..wbbbbbbbbbb...",
      "...dddddddbbb...",
      "....bS....Sb....",
      "................",
    ],
    crouch: [
      "................",
      "................",
      "................",
      "................",
      ".......gg...gg..",
      ".......bp...pb..",
      ".......bp...pb..",
      ".......bbbbbbb..",
      ".......bbbbbbbb.",
      ".......bwebbweb.",
      "....bbbbeebbeeb.",
      "...bbbbbbbbppbb.",
      "..wbbbbbbbbbbb..",
      "..wbbbbbbbbbb...",
      "...bbgS...Sb....",
      "................",
    ],
    jump: [
      "................",
      "................",
      ".......gg...gg..",
      ".......bp...pb..",
      ".......bp...pb..",
      ".......bbbbbbb..",
      ".......bbbbbbbb.",
      ".......bwebbweb.",
      "....bbbbeebbeeb.",
      "...bbbbbbbbppbb.",
      "..wbbbbbbbbbbb..",
      "..wbbbbbbbbbb...",
      "...dddddddbbb...",
      "..bS.......Sb...",
      ".bS.............",
      "................",
    ],
    fall: [
      "................",
      "................",
      ".......gg...gg..",
      ".......bp...pb..",
      ".......bp...pb..",
      ".......bbbbbbb..",
      ".......bbbbbbbb.",
      ".......bwebbweb.",
      "....bbbbeebbeeb.",
      "...bbbbbbbbppbb.",
      "..wbbbbbbbbbbb..",
      "..wbbbbbbbbbb...",
      "...dddddddbbb...",
      "...bS.....Sb....",
      "...bS.....Sb....",
      "................",
    ],
    sleep1: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "....bppppbb.....",
      "...bbbbbbbbbbb..",
      "..bbbbbbbbbbbbb.",
      "..bbbbbbbzzbzzb.",
      ".wbbbbbbbbbpbbb.",
      "..bbbbbbbbbbbbb.",
      "................",
    ],
    sleep2: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "....bppppbb.....",
      "..bbbbbbbbbbbb..",
      "..bbbbbbbbbbbbb.",
      "..bbbbbbbzzbzzb.",
      ".wbbbbbbbbbpbbb.",
      "..bbbbbbbbbbbbb.",
      "................",
    ],
    held: [
      "................",
      "................",
      "................",
      "...gg...gg......",
      "...bp...pb......",
      "...bp...pb......",
      "...bbbbbbb......",
      "...bbbbbbbb.....",
      "...bwebbweb.....",
      "...beebbeeb.....",
      "...bkbppbkb.....",
      "....bbbbbb......",
      "...bbbbbbb......",
      "...b.bbbb.b.....",
      "....bb..bb......",
      "................",
    ],
    happy: [
      "................",
      "................",
      "................",
      ".......gg...gg..",
      ".......bp...pb..",
      ".......bp...pb..",
      ".......bbbbbbb..",
      ".......bbbbbbbb.",
      ".......bbzbbzbb.",
      "....bbbbzbzzbzb.",
      "...bbbbbbbbppbb.",
      "..wbbbbbbbbbbb..",
      "..wbbbbbbbbbb...",
      "...dddddddbbb...",
      "...bbgS...Sb....",
      "................",
    ],
    nudge1: [
      "................",
      "................",
      "................",
      "................",
      ".......gg...gg..",
      ".......bp...pb..",
      ".......bp...pb..",
      ".......bbbbbbb..",
      ".......bbbbbbbb.",
      ".......bwebbweb.",
      "....bbbbeebbeeb.",
      "...bbbbbbbbppbb.",
      "..wbbbbbbbbbbb..",
      "..wbbbbbbbbbb...",
      "...bbgS...Sb....",
      "................",
    ],
    nudge2: [
      "................",
      "................",
      "................",
      "................",
      "........gg...gg.",
      "........bp...pb.",
      "........bp...pb.",
      "........bbbbbbb.",
      ".......bbbbbbbb.",
      ".......bwebbweb.",
      "....bbbbeebbeeb.",
      "...bbbbbbbbppbb.",
      "..wbbbbbbbbbbb..",
      "..wbbbbbbbbbb...",
      "...bbgS...Sb....",
      "................",
    ],
  },
};
