import type { SpeciesSprites } from "./types";

// Tabby cat, fills only (the outline is added at load). b fur, s stripe,
// d belly shade, S far-side legs (unoutlined), w cream (muzzle, paws, eye
// shine), e eye, z closed eye, p nose and inner ear, k cheek blush,
// o interior line.
export const cat: SpeciesSprites = {
  variants: {
    ginger: {
      label: "Ginger",
      colors: { b: "#e0904f", s: "#b5652f", S: "#a65a2a", w: "#f3dfc4", d: "#c97a3c", k: "#f0a28e", z: "#1f1a17", e: "#1f1a17", p: "#e48e9c" },
      outline: { light: "#3d2b22", dark: "#7a4a2c" },
    },
    grey: {
      label: "Grey tabby",
      colors: { b: "#a3a8b0", s: "#6f747d", S: "#7f848d", w: "#f1f2f4", d: "#8b9099", k: "#e9b0b8", z: "#1f1a17", e: "#1f1a17", p: "#e8a0ae" },
      outline: { light: "#2e3036", dark: "#5d6169" },
    },
    tuxedo: {
      label: "Tuxedo",
      colors: { b: "#3a3842", s: "#2a2830", S: "#2c2a33", w: "#eceaf0", d: "#302e37", k: "#c97a8a", z: "#141217", e: "#e2c044", p: "#e48e9c" },
      outline: { light: "#16151a", dark: "#8a8696" },
    },
  },
  frames: {
    idle1: [
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".s.....bbbssbbb.",
      ".b.....bwebbweb.",
      ".s.....beebbeeb.",
      ".b.bsbsbkwppwkb.",
      ".bbbsbsbbwwwwb..",
      "..bbbbbbbbwwb...",
      "..dddddddddbb...",
      "...bS.....Sb....",
      "...wS.....Sw....",
      "................",
    ],
    idle2: [
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".s.....bbbssbbb.",
      ".b.....bbbbbbbb.",
      ".s.....bzzbbzzb.",
      ".b.bsbsbkwppwkb.",
      ".bbbsbsbbwwwwb..",
      "..bbbbbbbbwwb...",
      "..dddddddddbb...",
      "...bS.....Sb....",
      "...wS.....Sw....",
      "................",
    ],
    sit: [
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".......bbbssbbb.",
      ".......bwebbweb.",
      "......bbeebbeeb.",
      ".....bsbkwppwkb.",
      "....bbbbbwwwwb..",
      "...bbsbbbbwwb...",
      "...bbbsbbbbbb...",
      "...bbbbbbobbb...",
      ".wbbbbbbbowww...",
      "................",
    ],
    walk1: [
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".s.....bbbssbbb.",
      ".b.....bwebbweb.",
      ".s.....beebbeeb.",
      ".b.bsbsbkwppwkb.",
      ".bbbsbsbbwwwwb..",
      "..bbbbbbbbwwb...",
      "..dddddddddbb...",
      "..b..S...S..b...",
      "..w..S...S..w...",
      "................",
    ],
    walk2: [
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".s.....bbbssbbb.",
      ".b.....bwebbweb.",
      ".s.....beebbeeb.",
      ".b.bsbsbkwppwkb.",
      ".bbbsbsbbwwwwb..",
      "..bbbbbbbbwwb...",
      "..dddddddddbb...",
      "...bS.....Sb....",
      "...wS.....Sw....",
      "................",
    ],
    walk3: [
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".s.....bbbssbbb.",
      ".b.....bwebbweb.",
      ".s.....beebbeeb.",
      ".b.bsbsbkwppwkb.",
      ".bbbsbsbbwwwwb..",
      "..bbbbbbbbwwb...",
      "..dddddddddbb...",
      "..S..b...b..S...",
      "..S..w...w..S...",
      "................",
    ],
    walk4: [
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".s.....bbbssbbb.",
      ".b.....bwebbweb.",
      ".s.....beebbeeb.",
      ".b.bsbsbkwppwkb.",
      ".bbbsbsbbwwwwb..",
      "..bbbbbbbbwwb...",
      "..dddddddddbb...",
      "...Sb.....bS....",
      "...Sw.....wS....",
      "................",
    ],
    crouch: [
      "................",
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".s.....bbbssbbb.",
      ".b.....bwebbweb.",
      ".s.....beebbeeb.",
      ".b.bsbsbkwppwkb.",
      ".bbbsbsbbwwwwb..",
      "..bbbbbbbbwwb...",
      "..dddddddddbb...",
      "...wS.....Sw....",
      "................",
    ],
    jump: [
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".s.....bbbssbbb.",
      ".b.....bwebbweb.",
      ".s.....beebbeeb.",
      ".b.bsbsbkwppwkb.",
      ".bbbsbsbbwwwwb..",
      "..bbbbbbbbwwb...",
      "..dddddddddbb...",
      "..Sb.......bS...",
      ".Sb.............",
      "Sw..............",
      "................",
    ],
    fall: [
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".s.....bbbssbbb.",
      ".b.....bwebbweb.",
      ".s.....beebbeeb.",
      ".b.bsbsbkwppwkb.",
      ".bbbsbsbbwwwwb..",
      "..bbbbbbbbwwb...",
      "..dddddddddbb...",
      "...Sb.....bS....",
      "..S.b.....b.S...",
      "..S.w.....w.S...",
      "................",
    ],
    sleep1: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbbbbbbb.",
      "....bbbbbsbbsbb.",
      "..bsbsbbbbssbbb.",
      ".bbbbbbbzzbbzzb.",
      ".bbbbbbbkwppwkb.",
      ".wbbbbbbbbwwbbb.",
      "................",
    ],
    sleep2: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      "...bbb.bbbbbbbb.",
      "..bbbbbbbsbbsbb.",
      "..bsbsbbbbssbbb.",
      ".bbbbbbbzzbbzzb.",
      ".bbbbbbbkwppwkb.",
      ".wbbbbbbbbwwbbb.",
      "................",
    ],
    held: [
      "................",
      "....b......b....",
      "....bp....pb....",
      "....bbbssbbb....",
      "....bwebbweb....",
      "....beebbeeb....",
      "....bkwppwkb....",
      ".....bwwwwb.....",
      ".....bbwwbb.....",
      ".....bbbbbb.....",
      "....b.bbbb.b....",
      "....b.bbbb.b....",
      ".....S.bb.S.....",
      ".......bb.......",
      "........w.......",
      "................",
    ],
    happy: [
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".s.....bbbssbbb.",
      ".b.....bbzbbzbb.",
      ".s.....bzbzzbzb.",
      ".b.bsbsbkwppwkb.",
      ".bbbsbsbbwwwwb..",
      "..bbbbbbbbwwb...",
      "..dddddddddbb...",
      "...bS.....Sb....",
      "...wS.....Sw....",
      "................",
    ],
    swat1: [
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".......bbbssbbb.",
      ".......bwebbweb.",
      "......bbeebbeeb.",
      ".....bsbkwppwkb.",
      "....bbbbbwwwwb..",
      "...bbsbbbbwwbww.",
      "...bbbsbbbbbb...",
      "...bbbbbbobb....",
      ".wbbbbbbboww....",
      "................",
    ],
    swat2: [
      "................",
      "................",
      "................",
      ".......b......b.",
      ".......bp....pb.",
      ".......bbsbbsbb.",
      ".......bbbssbbb.",
      ".......bwebbweb.",
      "......bbeebbeeb.",
      ".....bsbkwppwkb.",
      "....bbbbbwwwwb..",
      "...bbsbbbbwwb...",
      "...bbbsbbbbbbww.",
      "...bbbbbbobb....",
      ".wbbbbbbboww....",
      "................",
    ],
  },
};
