import type { SpeciesSprites } from "./types";

// Pup with floppy ears, fills only (the outline is added at load). b fur,
// h crown sheen, d brows and belly shade, s ears, S far-side legs (unoutlined),
// w cream muzzle, chest, paws and tail tip, c collar, y tag, e eye,
// z closed eye, n nose, p tongue, r ball, o interior line.
export const dog: SpeciesSprites = {
  variants: {
    golden: {
      label: "Golden",
      colors: { b: "#d8a76b", s: "#8c5a34", S: "#a8783f", w: "#f4e6cc", h: "#e8c08a", d: "#bf8c52", c: "#3f6fb5", y: "#f2c84b", z: "#1f1a17", e: "#1f1a17", n: "#2a1d17", p: "#e8798a", r: "#d9483b" },
      outline: { light: "#3a2a1f", dark: "#7a5434" },
    },
    chocolate: {
      label: "Chocolate",
      colors: { b: "#8a5a3b", s: "#5a3622", S: "#6a4329", w: "#ead7bf", h: "#a3714f", d: "#74492f", c: "#c94f4f", y: "#f2c84b", z: "#1f1a17", e: "#1f1a17", n: "#1f140d", p: "#e8798a", r: "#d9483b" },
      outline: { light: "#2a1a10", dark: "#4e3020" },
    },
    black: {
      label: "Black",
      colors: { b: "#3a3638", s: "#232022", S: "#2a2628", w: "#d9cfc4", h: "#55504f", d: "#2e2a2c", c: "#4fa36b", y: "#f2c84b", z: "#121011", e: "#c7954d", n: "#141113", p: "#e8798a", r: "#d9483b" },
      outline: { light: "#151314", dark: "#8a8386" },
    },
  },
  frames: {
    idle1: [
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      ".w.....sbebbebs.",
      ".b.....sbebbebs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwb..",
      "..bbbbbbccyccc..",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "...bS.....Sb....",
      "...wS.....Sw....",
      "................",
    ],
    idle2: [
      "................",
      "................",
      "................",
      "................",
      "........bbbbbb..",
      ".......sbbhhbbs.",
      "..w....sbdbbdbs.",
      "..b....sbzbbzbs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwb..",
      "..bbbbbbccyccc..",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "...bS.....Sb....",
      "...wS.....Sw....",
      "................",
    ],
    sit: [
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      ".......sbebbebs.",
      ".......sbebbebs.",
      "......bsbbbbbbs.",
      ".....bbbbwnnwb..",
      "....bbbbccyccc..",
      "...bbbbbbbwwb...",
      "...dddddddbbb...",
      "...bbbbbbobbb...",
      ".bbbbbbbbobbb...",
      "................",
    ],
    walk1: [
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      ".w.....sbebbebs.",
      ".b.....sbebbebs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwb..",
      "..bbbbbbccyccc..",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "..b..S...S..b...",
      "..w..S...S..w...",
      "................",
    ],
    walk2: [
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      "..w....sbebbebs.",
      "..b....sbebbebs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwb..",
      "..bbbbbbccyccc..",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "...bS.....Sb....",
      "...wS.....Sw....",
      "................",
    ],
    walk3: [
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      ".w.....sbebbebs.",
      ".b.....sbebbebs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwb..",
      "..bbbbbbccyccc..",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "..S..b...b..S...",
      "..S..w...w..S...",
      "................",
    ],
    walk4: [
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      "..w....sbebbebs.",
      "..b....sbebbebs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwb..",
      "..bbbbbbccyccc..",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "...Sb.....bS....",
      "...Sw.....wS....",
      "................",
    ],
    crouch: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      ".w.....sbebbebs.",
      ".b.....sbebbebs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwb..",
      "..bbbbbbccyccc..",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "...wS.....Sw....",
      "................",
    ],
    jump: [
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      ".w.....sbebbebs.",
      ".b.....sbebbebs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwb..",
      "..bbbbbbccyccc..",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "..Sb.......bS...",
      ".Sb.............",
      "Sw..............",
      "................",
    ],
    fall: [
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      ".w.....sbebbebs.",
      ".b.....sbebbebs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwb..",
      "..bbbbbbccyccc..",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "...Sb.....bS....",
      "..S.b.....b.S...",
      "..S.w.....w.S...",
      "................",
    ],
    sleep1: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbbhhbbs.",
      "....bbbsbbhhbbs.",
      "..bbbbbsbbbbbbs.",
      ".bbbbbbsbzzbzzb.",
      ".bbbbbbbbwnnwb..",
      ".bbbbbbbbwwwwbb.",
      "................",
    ],
    sleep2: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      "....bbbsbbhhbbs.",
      "..bbbbbsbbhhbbs.",
      "..bbbbbsbbbbbbs.",
      ".bbbbbbsbzzbzzb.",
      ".bbbbbbbbwnnwb..",
      ".bbbbbbbbwwwwbb.",
      "................",
    ],
    held: [
      "................",
      "................",
      "................",
      "....bbhhbb......",
      "...sbdbbdbs.....",
      "...sbebbebs.....",
      "...sbebbebs.....",
      "...sbbbbbbs.....",
      "....bwnnwb......",
      ".....ccyc.......",
      ".....bbbb.......",
      "....b.bb.b......",
      "....b.bb.b......",
      ".....S..S.......",
      ".......w........",
      "................",
    ],
    happy: [
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      "..w....sbzbbzbs.",
      "..b....szbzzbzs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwb..",
      "..bbbbbbccypcc..",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "...bS.....Sb....",
      "...wS.....Sw....",
      "................",
    ],
    carry1: [
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      ".w.....sbebbebs.",
      ".b.....sbebbebs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwrr.",
      "..bbbbbbccyccrr.",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "..b..S...S..b...",
      "..w..S...S..w...",
      "................",
    ],
    carry2: [
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      "..w....sbebbebs.",
      "..b....sbebbebs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwrr.",
      "..bbbbbbccyccrr.",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "...bS.....Sb....",
      "...wS.....Sw....",
      "................",
    ],
    carry3: [
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      ".w.....sbebbebs.",
      ".b.....sbebbebs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwrr.",
      "..bbbbbbccyccrr.",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "..S..b...b..S...",
      "..S..w...w..S...",
      "................",
    ],
    carry4: [
      "................",
      "................",
      "................",
      "................",
      "........bbhhbb..",
      ".......sbdbbdbs.",
      "..w....sbebbebs.",
      "..b....sbebbebs.",
      "..b.bbbsbbbbbbs.",
      "..bbbbbbbwnnwrr.",
      "..bbbbbbccyccrr.",
      "..bbbbbbbbwwb...",
      "...dddddddbbb...",
      "...Sb.....bS....",
      "...Sw.....wS....",
      "................",
    ],
  },
};
